// <auto-generated />
using System;
using Dishantha.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dishantha.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210829103805_Migration_1")]
    partial class Migration_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dishantha.Domain.Entities.Sighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AircraftPhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sightings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AircraftPhotoName = "b56b02aa-385d-42f2-8809-5f8d80c9ae71.png",
                            CreatedDateTime = new DateTimeOffset(new DateTime(2021, 8, 29, 16, 8, 5, 178, DateTimeKind.Unspecified).AddTicks(8180), new TimeSpan(0, 5, 30, 0, 0)),
                            DateAndTime = new DateTime(2010, 8, 28, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            Location = "London Gatwick",
                            Make = "AD Scout",
                            Model = "777-300ER",
                            Registration = "G-RNAC"
                        },
                        new
                        {
                            Id = 2,
                            AircraftPhotoName = "38dc45b2-0126-4657-9869-a1f8860b274f.png",
                            CreatedDateTime = new DateTimeOffset(new DateTime(2021, 8, 29, 16, 8, 5, 178, DateTimeKind.Unspecified).AddTicks(9665), new TimeSpan(0, 5, 30, 0, 0)),
                            DateAndTime = new DateTime(2010, 8, 28, 8, 25, 0, 0, DateTimeKind.Unspecified),
                            Location = "London Gatwick",
                            Make = "Aerfer Ariete",
                            Model = "777-302ER",
                            Registration = "G-RNAC"
                        },
                        new
                        {
                            Id = 3,
                            AircraftPhotoName = "bf98f2a3-d7c6-45c6-9481-a9ee844075f5.png",
                            CreatedDateTime = new DateTimeOffset(new DateTime(2021, 8, 29, 16, 8, 5, 178, DateTimeKind.Unspecified).AddTicks(9671), new TimeSpan(0, 5, 30, 0, 0)),
                            DateAndTime = new DateTime(2010, 8, 28, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "London Gatwick",
                            Make = "Beardmore W.B.V",
                            Model = "777-303ER",
                            Registration = "G-RNAC"
                        },
                        new
                        {
                            Id = 4,
                            AircraftPhotoName = "40ec6d2f-3bf3-4225-9c14-1d7b99096129.png",
                            CreatedDateTime = new DateTimeOffset(new DateTime(2021, 8, 29, 16, 8, 5, 178, DateTimeKind.Unspecified).AddTicks(9678), new TimeSpan(0, 5, 30, 0, 0)),
                            DateAndTime = new DateTime(2010, 8, 28, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            Location = "London Gatwick",
                            Make = "Dewoitine D.25",
                            Model = "777-304ER",
                            Registration = "G-RNAC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
